### ISSUE TITLE
Change bintray endpoints to x86_64 from amd64

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/ocdev#116]
This will help us writing the installation script, since `uname -m` returns x86_64 instead of amd64
@kadel can you help with this?

**Comment by kadel** [comment]
go compiler uses `amd64` so you will have to do some kind of mapping.
This will only move this mapping from installation script to Makefile. but it will be still required. 
Plus amd64 is now used in multiple places (see Makefile, and scripts in ./scripts)

**Comment by containscafeine** [comment]
I'm fine with keeping it
