### ISSUE TITLE
UC 6: As a developer, I want to do all my interactions in a context of “current application”

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/ocdev#151]
As a developer, I want to do all my interactions in a context of “current application”

As a developer using the command line tool, I want all of my interactions on the command line to be done in the context of the current application that I am working on/with.If no application exists, a default application will be created. 

```
$ ocd create php [name] [--git=]
Component <name> has been added to application <XYZ>
----
$ ocd create php:5.6 [name] 
There’s no application selected. Creating an application named “app”.
```

**Comment by slemeur** [comment]
Already in the foundations of the tool.
