### ISSUE TITLE
UC 18: As a developer, I want to have tab completion

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/ocdev#163]
As a developer, I want to have tab completion so that I don’t need to lookup options and available commands as I type, for bash and zsh shells.  

__*NOTE:*__ This can follow the current oc completions command as an example.

Tasks:
- [ ] #212 bash tab completion
- [ ] #213 zsh tab completion

Add issues for completion for missing commands

**Comment by kadel** [comment]
decompose this. Not important for MVP. It is just nice to have.

**Comment by cdrage** [comment]
Bash and ZSH completion has been added:
```
▶ ocdev completion --help
Generates shell completion code.

Auto completion supports both bash and zsh. Output is to STDOUT.

source <(ocdev completion bash)
source <(ocdev completion zsh)

Will load the shell completion code.

Usage:
  ocdev completion SHELL [flags]

Flags:
  -h, --help   help for completion

Global Flags:
  -v, --verbose   verbose output
```
