### ISSUE TITLE
ocdev app should return current app, not create it if non existent

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/ocdev#190]
On a new cluster, new config, new install.

```
$ ocdev app list
ACTIVE   NAME

$ ocdev app
The current application is: app

$ ocdev app list
ACTIVE   NAME
  *      app
```

The command has created the app, and use it as default current app.

See #152

**Comment by kadel** [comment]
related to https://github.com/redhat-developer/ocdev/issues/142

**Comment by kadel** [comment]
@jorgemoralespou Is is ok to have it like this?
```
$ ocdev app list
ACTIVE   NAME

$ ocdev app
The current application is: app

$ ocdev app list
ACTIVE   NAME
```

or should `ocdev app` return something like "No applications is set as current"?

**Comment by jorgemoralespou** [comment]
@kadel it's ok like that
