### ISSUE TITLE
When creating an app, use "app" as default name

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/ocdev#218]
When you create an app, name of the app is not mandatory. If not provided, use "app" (or random generated name when #216 is done) as default.

```
$ od create app
# This will create an app with name app
````

If there's already one app with that name in the current application, give an error before create anything.

```
$ oc create httpd
ERROR: There's already one app with than name (app-xyz). Provide a name as argument, or switch to that app
```

Subtask of #164

**Comment by kadel** [comment]
The first part is done.
But currently, we are not checking whatever application already exists or not.

**Comment by kadel** [comment]
related to https://github.com/redhat-developer/ocdev/issues/104

**Comment by kadel** [comment]
> If there's already one app with that name in the current application, give an error before create anything. 

I'm a little bit confused about this sentence.
Should this say "If there's already one **component** with that name in the current application, give an error before creating anything." ?

**Comment by kadel** [comment]
Check if Application doesn't exist is already there 
```
[mdas@localhost ocdev]$ ./ocdev app create app 
Creating application: app
unable to create new application: unable to add app application, it already exists in config file
```
