### ISSUE TITLE
Fail within ginko testing not os.Exit(1)

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/ocdev#316]
We should be failing using: https://onsi.github.io/ginkgo/#marking-specs-as-failed within our end-to-end tests rather than using: https://github.com/redhat-developer/ocdev/blob/master/tests/e2e/e2e_test.go#L41

I suggest that we modify https://github.com/redhat-developer/ocdev/blob/master/tests/e2e/e2e_test.go#L28 to return `err` and if it errors, use `Fail("Failure reason")` with the stderr output from the `ocdev` command.

**Comment by cdrage** [comment]
ping @ashetty1

**Comment by kadel** [comment]
When this issue gets fixed, please remove the verbose flag that was added in https://github.com/redhat-developer/ocdev/pull/308.

**Comment by cdrage** [comment]
Closing this as https://github.com/redhat-developer/ocdev/pull/320 was merged and then https://github.com/redhat-developer/ocdev/pull/322 (to remove the verbose output).

Closing this issue!
