### ISSUE TITLE
create homebrew package

### ISSUE THREAD

**Issue by kadel** [redhat-developer/ocdev#69]

**Comment by kadel** [comment]
https://github.com/redhat-developer/ocdev/issues/73 is prerequisite

**Comment by kadel** [comment]
homebrew-core is not accepting packages for project that are too new :-(
[Acceptable-Formulae](
https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#niche-or-self-submitted-stuff)

```
▶ brew audit --new-formula ocdev
ocdev:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
  * GitHub repository too new (<30 days old)
Error: 2 problems in 1 formula
```


I've created new Tap

https://github.com/kadel/homebrew-ocdev

now ocdev can be installed like this:
```
brew tap kadel/ocdev
brew install kadel/ocdev/ocdev
```

I'm not going to update docs with this, as we should find the right place for our homebrew tap, or wait until we can get into homebrew-core.

There was a discussion about moving ocdev to github.com/openshift, if we do that,  than can also move `kadel/homebrew-ocdev` to `openshift/homebrew-cli` and then it will be
 ```
brew tap openshift/cli
brew install openshift/cli/ocdev
```

**Comment by kadel** [comment]
what do you think @slemeur ?

**Comment by kadel** [comment]
most recent version (build from master) can be installed via
```
brew install openshift/cli/ocdev --HEAD
```

**Comment by slemeur** [comment]
Sounds good for me @kadel.
Thanks

**Comment by kadel** [comment]
installation is described in README #93

**Comment by zplewis** [comment]
How about now? It's been three years since this last post.

**Comment by kadel** [comment]
@zplewis There is a Homebrew Tap with odo 
https://github.com/kadel/homebrew-odo/

I'm also working on adding it to core homebrew, but we need to find a suitable name as there already is another package with odo name https://formulae.brew.sh/formula/odo

**Comment by zplewis** [comment]
How about openshift-odo?

Z. Patrick Lewis
ETL and Reporting Developer
Information Technology Services
P: 919-537-3746 | ***@***.***
ITS-Manning | UNC-Chapel Hill | Campus Box 3420 | Chapel Hill, NC 27599
________________________________

**Comment by kadel** [comment]
> How about openshift-odo?

we don't want to use openshift in the name anymore. So we will probably go  with odo-dev or odo-cli

**Comment by zplewis** [comment]
> > How about openshift-odo?
> 
> we don't want to use openshift in the name anymore. So we will probably go with odo-dev or odo-cli

That works! Thanks for working on this and being responsive in your replies. I look forward to when this is added to core homebrew.
