### ISSUE TITLE
Create installation bash script

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/ocdev#74]
We should have bash script that takes care of installing ocdev in your $PATH. It also determines if `oc` binary is present or not, and installs it if absent.

**Comment by kadel** [comment]
context from #70:

We need to think about the getting started experience of the end-user with ocdev and try to provide the best first experience. This implies a certain requirements on how the user can install ocdev as well as a flow in the documentation to help the user to quickly ramp up.

The installation of ocdev is requiring some pre-requisites that we need to document.

Once those pre-requisites are installed, we should be looking at how we can simplify the installation of ocdev. For example, on MacOS, we could be using homebrew packages, on Linux we could install from a single command line wget -qO- https://github.com/redhat-developer/ocdev/master/blob/install-ocdev.sh | sh . This should be properly documented too.

**Comment by kadel** [comment]
the script should also handle uninstallation / cleaning

**Comment by containscafeine** [comment]
From #70 
We need to provide a way for the developer to properly uninstall ocdev.
If ocdev was installed with homebrew, we can have an uninstall command.
We should provide proper set of instructions to delete on Linux and Windows too.

**Comment by kadel** [comment]
closed in #117 

future improvements described in #124
