### ISSUE TITLE
Copyright contains "NAME HERE <EMAIL ADDRESS>" instead of the real value

### ISSUE THREAD

**Issue by apupier** [redhat-developer/ocdev#79]
for instance
https://github.com/redhat-developer/ocdev/blob/00a364e44c12868f0fc27568f8e4b63b6a76a347/cmd/application.go#L1
https://github.com/redhat-developer/ocdev/blob/00a364e44c12868f0fc27568f8e4b63b6a76a347/cmd/completion.go#L1

**Comment by kadel** [comment]
fixed in https://github.com/redhat-developer/ocdev/pull/131
