### ISSUE TITLE
Build a `oc` wrapper library of sorts

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/ocdev#8]
We need to build a wrapper around the `oc` commands that we will frequently use instead of always execing to `oc`.
Ideal case would be to use https://github.com/openshift/client-go, but AFAIK it does have support for all the `oc` commands, so till happens, we will need a wrapper which we can easily replace later on.

This could very well be a different package or even a project outside which we simply import.

**Comment by kadel** [comment]
can we close this, or do you want to keep it open?
