### ISSUE TITLE
Labels for app and component should be the standard

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/ocdev#85]
When creating applications on OpenShift/K8S, there's currently one label that is standard "app" and that the OpenSHift UI uses to group components that belong to the same application. OpenShift/K8S are trying to standardize on other labels, (e.g. component), and this should be used, so that the application is properly visualized, and in the future, managed with other tools.

I have created an application called devconfcz18 and then a component called httpd.

This are the labels set on the deployment:
![screen shot 2018-02-13 at 17 08 44](https://user-images.githubusercontent.com/78350/36160343-3b397684-10e1-11e8-931a-e89bdfb26899.png)

And this is what can be seen in the Overview.
![screen shot 2018-02-13 at 17 12 35](https://user-images.githubusercontent.com/78350/36160326-330448b8-10e1-11e8-9b1e-59dd13c18b56.png)

As can be seen in the second image, OpenShift identifies the application as "httpd" and not as "devconfcz18"

**Comment by sspeiche** [comment]
+1 to standardizing

There already exists "app", so no reason to add app.ocdev.... .

Labeling (both core OpenShift and ocdev) should align with the sig-apps proposal as well.

**Comment by kadel** [comment]
yep, we will fix app label.

But is it ok to use `app` for internal operations that `ocdev` does? Like listing and deleting objects.
If we do those operations according to app label, then we could easily delete something that we didn't created

**Comment by sspeiche** [comment]
>
> But is it ok to use app for internal operations that ocdev does? Like
> listing and deleting objects.
> If we do those operations according to app label, then we could easily
> delete something that we didn't created
>
I think app is fine for now, that is what we are using in OpenShift web
console. If there is something we should switch to, we'd coordinate.
