### ISSUE TITLE
add project commads

### ISSUE THREAD

**Issue by kadel** [redhat-developer/ocdev#96]
`ocdev project create <project_name>`
`ocdev project set <project_name>`
`ocdev project`

project maps to normal openshift project

**Comment by jorgemoralespou** [comment]
Why replicate this command? ocdev is supposed to work in the context of a project, and oc can be used to call the project. I would not target MVP for this.

**Comment by kadel** [comment]
OK, we will skip that for now. 
I was just looking at use case 23 where are commands like this.

**Comment by containscafeine** [comment]
@mik-dass do you want to take a stab at this?

**Comment by mik-dass** [comment]
@containscafeine Sure, I will look into this.
