### ISSUE TITLE
Switch to `openshift/client-go` at some point

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/ocdev#98]
Also consider discussions at https://github.com/openshift/client-go/issues/25

**Comment by kadel** [comment]
Will also need parts of `oc` client code. For example `oc new-app` logic is only on client side inside `oc` command itself and not in `client-go`

**Comment by containscafeine** [comment]
@kadel how about researching this for now?

**Comment by containscafeine** [comment]
This might be a blocker of sorts - https://github.com/openshift/client-go/issues/30

**Comment by kadel** [comment]
That is something that we already discussed multiple times. 
Functionality like `oc new-app` is only in `oc` client and quite possibly it will never go to server-side api. 

We can't just switch to `client-go` without also using and importing parts of `oc` client.

In future, this will be less and less issue, as ocdev will have much more functionality than oc right now have so we will have to move away from `oc` anyway. `oc new-app` is just a temporary solution that soon won't be enought

**Comment by kadel** [comment]
tracked in https://github.com/redhat-developer/ocdev/issues/257
